import { useEffect, useMemo, useRef, useState, type CSSProperties, type DragEvent, type PointerEvent } from "react";
import { HerculesEngine, type LegalTarget } from "../engine/api.js";
import type { EngineCommand } from "../engine/commands/types.js";
import type { Difficulty, GameState } from "../engine/state/types.js";
import { moodPresentation, presentationEventsFromTransitions, type GameplayPresentation } from "./presentation.js";
import "./playtest.css";
import "./context.css";

const SAVE_KEY = "hercules-12-labors.playtest.save.v1";
const TRAY_ORDER_KEY = "hercules-12-labors.playtest.tray-order.v1";
const CONTROL_MODE_KEY = "hercules-12-labors.playtest.control-mode.v1";
let fallbackSeedCounter = 0;
const randomSeed = (): string => { const values = new Uint32Array(2); if (globalThis.crypto?.getRandomValues) { globalThis.crypto.getRandomValues(values); return `playtest-${values[0].toString(36)}-${values[1].toString(36)}`; } fallbackSeedCounter += 1; return `playtest-${Date.now().toString(36)}-${fallbackSeedCounter.toString(36)}`; };
const freshGame = () => HerculesEngine.createGame({ difficulty: "human", seed: randomSeed() }).state;
const persistGame = (state: GameState): boolean => { try { window.localStorage.setItem(SAVE_KEY, JSON.stringify(HerculesEngine.serialize(state))); return true; } catch { return false; } };
const loadGame = (): { state: GameState; restored: boolean } => { try { const saved = window.localStorage.getItem(SAVE_KEY); return saved ? { state: HerculesEngine.deserialize(JSON.parse(saved)), restored: true } : { state: freshGame(), restored: false }; } catch { window.localStorage.removeItem(SAVE_KEY); return { state: freshGame(), restored: false }; } };
const loadTrayOrder = (): string[] => { try { const saved = JSON.parse(window.localStorage.getItem(TRAY_ORDER_KEY) ?? "[]"); return Array.isArray(saved) && saved.every(id => typeof id === "string") ? saved : []; } catch { return []; } };
const loadControlMode = (): "drag" | "tap" => { try { return window.localStorage.getItem(CONTROL_MODE_KEY) === "tap" ? "tap" : "drag"; } catch { return "drag"; } };
const reconcileTrayOrder = (order: string[], knownIds: string[]) => { const known = new Set(knownIds); return [...order.filter(id => known.has(id)), ...knownIds.filter(id => !order.includes(id))]; };
const download = (name: string, value: unknown) => { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); };
const dieLabel = (id: string) => id.includes("-D") ? "Derived die" : id.startsWith("labor.") ? "Labor Die" : "Hercules die";
const romanNumeral = (value: number | null | undefined): string => {
  if (!value || value < 1 || value > 3999) return "—";
  const numerals: [number, string][] = [[1000, "M"], [900, "CM"], [500, "D"], [400, "CD"], [100, "C"], [90, "XC"], [50, "L"], [40, "XL"], [10, "X"], [9, "IX"], [5, "V"], [4, "IV"], [1, "I"]];
  let remaining = value;
  return numerals.map(([amount, symbol]) => {
    const count = Math.floor(remaining / amount);
    remaining %= amount;
    return symbol.repeat(count);
  }).join("");
};
const laborNumeral = (laborId: string | undefined): string => romanNumeral(laborId ? Number(laborId.match(/\d+/)?.[0]) : undefined);
const moodCompact = (id: string | null): string => ({
  "mood.melancholic": "🎲−1",
  "mood.enraged": "🎲+1",
  "mood.resolute": "⬢+1",
  "mood.battered": "⬢−1",
  "mood.weight_of_atlas": "⬢−2",
  "mood.ferocious": "◆ any",
  "mood.haunted_a": "♥−2",
  "mood.haunted_b": "♥−1",
  "mood.haunted_c": "♥−3",
  "mood.haunted_d": "♥−2",
  "mood.ghost_abderus": "⚖",
  "mood.ghost_hippolyta": "⚀⊘↻",
  "mood.ghost_pholus": "⛔"
}[id ?? ""] ?? "—");
type DragPreview = { pieceIds: string[]; x: number; y: number };
type SnapbackPreview = DragPreview & { originX: number; originY: number; returning: boolean; startScale: number };
type PendingCows = { abilityId: "ability.reward.L05.A.blue" | "ability.reward.L05.B.blue"; sourceDieId: string; targetDieId?: string };

function Die({ id, face, selected, targetable, disabled, draggable, state, dragging, onSelect, onDragStart, onDragOver, onDrop, onPointerDown, onPointerMove, onPointerUp, onPointerCancel }: { id: string; face: number | null; selected: boolean; targetable: boolean; disabled: boolean; draggable: boolean; state: string; dragging: boolean; onSelect: () => void; onDragStart: (event: DragEvent<HTMLButtonElement>) => void; onDragOver: (event: DragEvent<HTMLButtonElement>) => void; onDrop: (event: DragEvent<HTMLButtonElement>) => void; onPointerDown: (event: PointerEvent<HTMLButtonElement>) => void; onPointerMove: (event: PointerEvent<HTMLButtonElement>) => void; onPointerUp: (event: PointerEvent<HTMLButtonElement>) => void; onPointerCancel: () => void }) {
  return <button data-tray-die={id} className={`die-tile ${selected ? "is-selected" : ""} ${targetable ? "is-targetable" : ""} ${dragging ? "is-dragging" : ""} ${disabled ? "is-disabled" : ""}`} style={{ touchAction: draggable ? "none" : "manipulation", userSelect: "none", opacity: dragging ? 0.68 : undefined, transform: dragging ? "scale(1.07)" : undefined }} disabled={disabled} draggable={draggable && !disabled} onClick={onSelect} onDragStart={onDragStart} onDragOver={onDragOver} onDrop={onDrop} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={onPointerCancel} aria-label={`${dieLabel(id)}, ${face ?? "unrolled"}, ${state}`}><strong>{face ?? "—"}</strong></button>;
}

function App() {
  const [loaded] = useState(loadGame);
  const [state, setState] = useState<GameState>(loaded.state);
  const [presentationQueue, setPresentationQueue] = useState<GameplayPresentation[]>([]);
  const seenTransitionCount = useRef(loaded.state.transitions.length);
  const needsInitialMoodPresentation = useRef(!loaded.restored);
  const [selectedDecisionId, setSelectedDecisionId] = useState<string | null>(null);
  const [difficulty, setDifficulty] = useState<Difficulty>(loaded.state.game.difficulty);
  const [seed, setSeed] = useState(loaded.state.rng.seed);
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [trayOrder, setTrayOrder] = useState<string[]>(loadTrayOrder);
  const [controlMode, setControlMode] = useState<"drag" | "tap">(loadControlMode);
  const [targetId, setTargetId] = useState<string | null>(null);
  const [editingAttackIndex, setEditingAttackIndex] = useState<number | null>(null);
  const [editingGoldAbilityId, setEditingGoldAbilityId] = useState<string | null>(null);
  const [touchDragging, setTouchDragging] = useState(false);
  const [bundleDragging, setBundleDragging] = useState(false);
  const [goldDragging, setGoldDragging] = useState(false);
  const [dragPreview, setDragPreview] = useState<DragPreview | null>(null);
  const [snapbackPreview, setSnapbackPreview] = useState<SnapbackPreview | null>(null);
  const [pendingCows, setPendingCows] = useState<PendingCows | null>(null);
  const actionGridRef = useRef<HTMLElement | null>(null);
  const touchGesture = useRef<{ pointerId: number; startX: number; startY: number; originX: number; originY: number; dieIds: string[]; moved: boolean } | null>(null);
  const bundleGesture = useRef<{ pointerId: number; startX: number; startY: number; originX: number; originY: number; allocationIndex: number; moved: boolean } | null>(null);
  const goldGesture = useRef<{ pointerId: number; startX: number; startY: number; originX: number; originY: number; abilityId: string; moved: boolean } | null>(null);
  const snapbackTimer = useRef<number | null>(null);
  const suppressTouchClick = useRef(false);
  const suppressBundleClick = useRef(false);
  const suppressGoldClick = useRef(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [moodDetailsOpen, setMoodDetailsOpen] = useState(false);
  const [debug, setDebug] = useState(false);
  const model = useMemo(() => HerculesEngine.getGameplayScreenModel(state, selectedIds), [state, selectedIds]);
  const { view } = model;
  const phaseAllowsSelection = view.game.phase === "BLUE_ABILITY_WINDOW" || view.game.phase === "GOLD_AND_ATTACK_PLACEMENT";
  const parkedCopyIdsByAbility = new Map<string, string[]>();
  if (view.game.phase === "BLUE_ABILITY_WINDOW") for (const copy of view.derivedContributions.filter(candidate => !candidate.allocated)) {
    const sourcePlacement = view.dice[copy.sourceDieId]?.placement as { kind?: string; abilityId?: string } | null;
    if (sourcePlacement?.kind !== "blue" || !sourcePlacement.abilityId) continue;
    parkedCopyIdsByAbility.set(sourcePlacement.abilityId, [...(parkedCopyIdsByAbility.get(sourcePlacement.abilityId) ?? []), copy.id]);
  }
  const parkedCopyIds = new Set([...parkedCopyIdsByAbility.values()].flat());
  // A die belongs to its committed attack or Gold tile, not as a disabled ghost in the tray.
  const physicalDice = Object.values(view.dice).filter(die => die.availableForLabor && !die.allocated && !die.locked && die.id !== pendingCows?.sourceDieId && !(view.game.phase === "BLUE_ABILITY_WINDOW" && typeof die.placement === "object" && die.placement !== null && (die.placement as { kind?: string }).kind === "blue"));
  const trayDice = [...physicalDice, ...view.derivedContributions.filter(die => !die.allocated && !parkedCopyIds.has(die.id))];
  const trayDiceById = new Map(trayDice.map(die => [die.id, die]));
  const knownTrayIds = [...Object.keys(view.dice), ...view.derivedContributions.map(die => die.id)];
  const orderedTrayDice = reconcileTrayOrder(trayOrder, knownTrayIds).flatMap(id => { const die = trayDiceById.get(id); return die ? [die] : []; });
  const editableAttackTargets = useMemo(() => editingAttackIndex === null ? [] : HerculesEngine.getEditableAttackTargets(state, editingAttackIndex), [editingAttackIndex, state]);
  const editableGoldTargets = useMemo(() => editingGoldAbilityId === null ? [] : HerculesEngine.getEditableGoldTargets(state, editingGoldAbilityId), [editingGoldAbilityId, state]);
  const interactionTargets = editingAttackIndex !== null ? editableAttackTargets : editingGoldAbilityId !== null ? editableGoldTargets : model.legalTargets;
  const selectedTarget = interactionTargets.find(target => target.id === targetId) ?? null;
  const activePresentation = presentationQueue[0] ?? null;
  const targetById = (id: string) => interactionTargets.find(target => target.id === id);
  const dismissPresentation = () => setPresentationQueue(current => current.slice(1));
  const submit = (command: EngineCommand) => { try { const result = HerculesEngine.submit(state, command); if (command.type === "UNDO_DETERMINISTIC") setPresentationQueue([]); setState(result.state); persistGame(result.state); setPendingCows(null); setSelectedIds([]); setTargetId(null); setEditingAttackIndex(null); setEditingGoldAbilityId(null); } catch { /* The engine owns legality; invalid gestures simply return visually. */ } };
  const start = (nextSeed = randomSeed()) => { const next = HerculesEngine.createGame({ difficulty, seed: nextSeed }).state; const nextMood = HerculesEngine.getPlayView(next).mood; setSeed(nextSeed); seenTransitionCount.current = next.transitions.length; setState(next); setTrayOrder(Object.keys(next.herculesDice)); persistGame(next); setPresentationQueue(nextMood.id && nextMood.name ? [moodPresentation(`setup:${nextMood.id}`, nextMood.name, nextMood.effect)] : []); setPendingCows(null); setSelectedDecisionId(null); setSelectedIds([]); setTargetId(null); };
  useEffect(() => { persistGame(state); }, [state]);
  useEffect(() => { setTrayOrder(current => reconcileTrayOrder(current, knownTrayIds)); }, [knownTrayIds.join("|")]);
  useEffect(() => { try { window.localStorage.setItem(TRAY_ORDER_KEY, JSON.stringify(trayOrder)); } catch { /* Local ordering is optional. */ } }, [trayOrder]);
  useEffect(() => { try { window.localStorage.setItem(CONTROL_MODE_KEY, controlMode); } catch { /* Control preference is optional. */ } }, [controlMode]);
  useEffect(() => { if (!needsInitialMoodPresentation.current) return; needsInitialMoodPresentation.current = false; if (view.mood.id && view.mood.name) setPresentationQueue([moodPresentation(`setup:${view.mood.id}`, view.mood.name, view.mood.effect)]); }, [view.mood.effect, view.mood.id, view.mood.name]);
  useEffect(() => { const transitions = state.transitions.slice(seenTransitionCount.current); seenTransitionCount.current = state.transitions.length; const presentations = presentationEventsFromTransitions(transitions); if (presentations.length) setPresentationQueue(current => [...current, ...presentations]); }, [state.transitions]);
  useEffect(() => { setSelectedDecisionId(null); }, [view.pendingDecision?.id]);
  const toggle = (id: string) => { if (suppressTouchClick.current || !phaseAllowsSelection) return; setEditingAttackIndex(null); setEditingGoldAbilityId(null); setTargetId(null); setSelectedIds(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]); };
  const beginDrag = (event: DragEvent<HTMLButtonElement>, id: string) => { event.dataTransfer.setData("application/x-hercules-tray-die", id); event.dataTransfer.effectAllowed = "move"; if (!selectedIds.includes(id)) setSelectedIds([id]); setTargetId(null); };
  const reorderTrayDie = (sourceId: string, targetId: string) => { if (sourceId === targetId) return; setTrayOrder(current => { const order = reconcileTrayOrder(current, knownTrayIds); if (!order.includes(sourceId) || !order.includes(targetId)) return order; const withoutSource = order.filter(id => id !== sourceId); const targetIndex = withoutSource.indexOf(targetId); return [...withoutSource.slice(0, targetIndex), sourceId, ...withoutSource.slice(targetIndex)]; }); };
  const trayDrop = (event: DragEvent<HTMLButtonElement>, targetId: string) => { const sourceId = event.dataTransfer.getData("application/x-hercules-tray-die"); if (!sourceId) return; event.preventDefault(); reorderTrayDie(sourceId, targetId); };
  const drop = (event: DragEvent, target: LegalTarget | undefined) => { event.preventDefault(); const attackText = event.dataTransfer.getData("application/x-hercules-attack-allocation"); const allocationIndex = Number(attackText); if (Number.isInteger(allocationIndex) && attackText !== "") { const editableTarget = HerculesEngine.getEditableAttackTargets(state, allocationIndex).find(candidate => candidate.id === target?.id); if (editableTarget?.commands.length === 1) submit(editableTarget.commands[0]); return; } const goldAbilityId = event.dataTransfer.getData("application/x-hercules-gold-placement"); if (goldAbilityId) { const editableTarget = HerculesEngine.getEditableGoldTargets(state, goldAbilityId).find(candidate => candidate.id === target?.id); if (editableTarget?.commands.length === 1) submit(editableTarget.commands[0]); return; } if (!target) return; if (target.commands.length === 1) submit(target.commands[0]); else setTargetId(target.id); };
  const originOf = (element: HTMLElement) => { const bounds = element.getBoundingClientRect(); return { x: bounds.left + bounds.width / 2, y: bounds.top + bounds.height / 2 }; };
  const trayCenter = () => { const tray = document.querySelector<HTMLElement>(".dice-tray"); if (!tray) return { x: window.innerWidth / 2, y: window.innerHeight - 72 }; return originOf(tray); };
  const previewScaleOf = (element: HTMLElement, pieceIds: string[]) => { const bounds = element.getBoundingClientRect(); const previewWidth = pieceIds.length * 52 + Math.max(0, pieceIds.length - 1) * 5; return Math.min(1, Math.max(0.38, Math.min(bounds.width / previewWidth, bounds.height / 52))); };
  const snapback = (pieceIds: string[], x: number, y: number, originX: number, originY: number, onComplete?: () => void, startScale = 1) => { if (snapbackTimer.current !== null) window.clearTimeout(snapbackTimer.current); setSnapbackPreview({ pieceIds, x, y, originX, originY, returning: false, startScale }); window.requestAnimationFrame(() => window.requestAnimationFrame(() => setSnapbackPreview(current => current ? { ...current, returning: true } : null))); snapbackTimer.current = window.setTimeout(() => { setSnapbackPreview(null); snapbackTimer.current = null; onComplete?.(); }, 220); };
  const chooseLegalTarget = (target: LegalTarget | null | undefined) => { if (!target) return; if (target.commands.length === 1) submit(target.commands[0]); else setTargetId(target.id); };
  const cowsAbility = (id: string): PendingCows["abilityId"] | null => id === "ability.reward.L05.A.blue" || id === "ability.reward.L05.B.blue" ? id : null;
  const canArmCows = (abilityId: string, sourceDieId: string) => { const cows = cowsAbility(abilityId); return !!cows && view.actions.some(action => (action.command.type === "USE_COWS_A" || action.command.type === "USE_COWS_B") && cows === abilityId && action.command.sourceDieId === sourceDieId); };
  const armCows = (abilityId: string, sourceDieId: string) => { const cows = cowsAbility(abilityId); if (!cows || !canArmCows(cows, sourceDieId)) return; setPendingCows({ abilityId: cows, sourceDieId }); setSelectedIds([]); setTargetId(null); };
  const cowsTargetIds = new Set(pendingCows ? view.actions.flatMap(action => {
    if (pendingCows.abilityId === "ability.reward.L05.A.blue" && action.command.type === "USE_COWS_A" && action.command.sourceDieId === pendingCows.sourceDieId) return [action.command.targetDieId];
    if (pendingCows.abilityId === "ability.reward.L05.B.blue" && action.command.type === "USE_COWS_B" && action.command.sourceDieId === pendingCows.sourceDieId) return action.command.rerollDieIds;
    return [];
  }) : []);
  const chooseCowsTarget = (targetDieId: string) => { if (!pendingCows || !cowsTargetIds.has(targetDieId)) return; if (pendingCows.abilityId === "ability.reward.L05.A.blue") { setPendingCows(current => current ? { ...current, targetDieId } : null); return; } const command = view.actions.find(action => action.command.type === "USE_COWS_B" && action.command.sourceDieId === pendingCows.sourceDieId && action.command.rerollDieIds.length === 1 && action.command.rerollDieIds[0] === targetDieId)?.command; if (command) submit(command); };
  const beginTouchDrag = (event: PointerEvent<HTMLButtonElement>, id: string) => { if (controlMode !== "drag" || event.pointerType !== "touch" || !phaseAllowsSelection) return; const origin = originOf(event.currentTarget); touchGesture.current = { pointerId: event.pointerId, startX: event.clientX, startY: event.clientY, originX: origin.x, originY: origin.y, dieIds: selectedIds.includes(id) && selectedIds.length > 1 ? selectedIds : [id], moved: false }; event.currentTarget.setPointerCapture(event.pointerId); };
  const autoScrollGameplay = (clientY: number) => { const grid = actionGridRef.current; if (!grid) return; const bounds = grid.getBoundingClientRect(); const edge = 70; if (clientY < bounds.top + edge) grid.scrollTop -= Math.ceil((bounds.top + edge - clientY) / 5); else if (clientY > bounds.bottom - edge) grid.scrollTop += Math.ceil((clientY - (bounds.bottom - edge)) / 5); };
  const moveTouchDrag = (event: PointerEvent<HTMLButtonElement>) => { const gesture = touchGesture.current; if (!gesture || gesture.pointerId !== event.pointerId || event.pointerType !== "touch") return; if (!gesture.moved && Math.hypot(event.clientX - gesture.startX, event.clientY - gesture.startY) > 8) { gesture.moved = true; setSelectedIds(gesture.dieIds); setTargetId(null); setTouchDragging(true); } if (gesture.moved) { setDragPreview({ pieceIds: gesture.dieIds, x: event.clientX, y: event.clientY }); autoScrollGameplay(event.clientY); } };
  const endTouchDrag = (event: PointerEvent<HTMLButtonElement>) => { const gesture = touchGesture.current; if (!gesture || gesture.pointerId !== event.pointerId || event.pointerType !== "touch") return; touchGesture.current = null; setTouchDragging(false); setDragPreview(null); if (!gesture.moved) return; suppressTouchClick.current = true; window.setTimeout(() => { suppressTouchClick.current = false; }, 0); const sourceId = gesture.dieIds.length === 1 ? gesture.dieIds[0] : null; const trayTargetId = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-tray-die]")?.dataset.trayDie; if (sourceId && trayTargetId && sourceId !== trayTargetId) { reorderTrayDie(sourceId, trayTargetId); setSelectedIds([sourceId]); return; } const dropId = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-drop-target]")?.dataset.dropTarget; if (sourceId && dropId && canArmCows(dropId.replace(/^blue:/, ""), sourceId)) { armCows(dropId.replace(/^blue:/, ""), sourceId); return; } const target = HerculesEngine.getLegalTargets(state, gesture.dieIds).find(candidate => candidate.id === dropId); if (!target) { snapback(gesture.dieIds, event.clientX, event.clientY, gesture.originX, gesture.originY); setSelectedIds(gesture.dieIds); return; } if (target.commands.length === 1) submit(target.commands[0]); else { setSelectedIds(gesture.dieIds); setTargetId(target.id); } };
  const cancelTouchDrag = () => { touchGesture.current = null; setTouchDragging(false); setDragPreview(null); };
  const beginBundleTouchDrag = (event: PointerEvent<HTMLButtonElement>, allocationIndex: number) => { if (controlMode !== "drag" || event.pointerType !== "touch") return; const origin = originOf(event.currentTarget); bundleGesture.current = { pointerId: event.pointerId, startX: event.clientX, startY: event.clientY, originX: origin.x, originY: origin.y, allocationIndex, moved: false }; event.currentTarget.setPointerCapture(event.pointerId); };
  const moveBundleTouchDrag = (event: PointerEvent<HTMLButtonElement>) => { const gesture = bundleGesture.current; if (!gesture || gesture.pointerId !== event.pointerId || event.pointerType !== "touch") return; const allocation = state.round.attackAllocations[gesture.allocationIndex]; if (!gesture.moved && Math.hypot(event.clientX - gesture.startX, event.clientY - gesture.startY) > 8) { gesture.moved = true; setSelectedIds([]); setTargetId(null); setEditingAttackIndex(gesture.allocationIndex); setBundleDragging(true); } if (gesture.moved) { setDragPreview({ pieceIds: allocation ? [...allocation.dieIds, ...allocation.contributionIds] : [], x: event.clientX, y: event.clientY }); autoScrollGameplay(event.clientY); } };
  const endBundleTouchDrag = (event: PointerEvent<HTMLButtonElement>) => { const gesture = bundleGesture.current; if (!gesture || gesture.pointerId !== event.pointerId || event.pointerType !== "touch") return; bundleGesture.current = null; setBundleDragging(false); setDragPreview(null); suppressBundleClick.current = true; window.setTimeout(() => { suppressBundleClick.current = false; }, 0); const allocation = state.round.attackAllocations[gesture.allocationIndex]; const pieceIds = allocation ? [...allocation.dieIds, ...allocation.contributionIds] : []; if (!gesture.moved) { const tray = trayCenter(); snapback(pieceIds, gesture.originX, gesture.originY, tray.x, tray.y, () => submit({ type: "REMOVE_ATTACK_ALLOCATION", allocationIndex: gesture.allocationIndex }), previewScaleOf(event.currentTarget, pieceIds)); return; } const dropId = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-drop-target]")?.dataset.dropTarget; const target = HerculesEngine.getEditableAttackTargets(state, gesture.allocationIndex).find(candidate => candidate.id === dropId); if (target?.commands.length === 1) submit(target.commands[0]); else { snapback(pieceIds, event.clientX, event.clientY, gesture.originX, gesture.originY); setEditingAttackIndex(null); } };
  const cancelBundleTouchDrag = () => { bundleGesture.current = null; setBundleDragging(false); setDragPreview(null); };
  const beginGoldTouchDrag = (event: PointerEvent<HTMLButtonElement>, abilityId: string) => { if (controlMode !== "drag" || event.pointerType !== "touch") return; const origin = originOf(event.currentTarget); goldGesture.current = { pointerId: event.pointerId, startX: event.clientX, startY: event.clientY, originX: origin.x, originY: origin.y, abilityId, moved: false }; event.currentTarget.setPointerCapture(event.pointerId); };
  const moveGoldTouchDrag = (event: PointerEvent<HTMLButtonElement>) => { const gesture = goldGesture.current; if (!gesture || gesture.pointerId !== event.pointerId || event.pointerType !== "touch") return; const placement = state.round.goldPlacements.find(candidate => candidate.abilityId === gesture.abilityId); if (!gesture.moved && Math.hypot(event.clientX - gesture.startX, event.clientY - gesture.startY) > 8) { gesture.moved = true; setSelectedIds([]); setTargetId(null); setEditingGoldAbilityId(gesture.abilityId); setGoldDragging(true); } if (gesture.moved) { setDragPreview({ pieceIds: placement ? [...placement.dieIds, ...placement.contributionIds] : [], x: event.clientX, y: event.clientY }); autoScrollGameplay(event.clientY); } };
  const endGoldTouchDrag = (event: PointerEvent<HTMLButtonElement>) => { const gesture = goldGesture.current; if (!gesture || gesture.pointerId !== event.pointerId || event.pointerType !== "touch") return; goldGesture.current = null; setGoldDragging(false); setDragPreview(null); suppressGoldClick.current = true; window.setTimeout(() => { suppressGoldClick.current = false; }, 0); const placement = state.round.goldPlacements.find(candidate => candidate.abilityId === gesture.abilityId); const pieceIds = placement ? [...placement.dieIds, ...placement.contributionIds] : []; if (!gesture.moved) { const tray = trayCenter(); snapback(pieceIds, gesture.originX, gesture.originY, tray.x, tray.y, () => submit({ type: "REMOVE_GOLD_PLACEMENT", abilityId: gesture.abilityId }), previewScaleOf(event.currentTarget, pieceIds)); return; } const dropId = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-drop-target]")?.dataset.dropTarget; const target = HerculesEngine.getEditableGoldTargets(state, gesture.abilityId).find(candidate => candidate.id === dropId); if (target?.commands.length === 1) submit(target.commands[0]); else { snapback(pieceIds, event.clientX, event.clientY, gesture.originX, gesture.originY); setEditingGoldAbilityId(null); } };
  const cancelGoldTouchDrag = () => { goldGesture.current = null; setGoldDragging(false); setDragPreview(null); };
  const ctaAction = () => { if (controlMode === "tap" && editingAttackIndex !== null) { submit({ type: "REMOVE_ATTACK_ALLOCATION", allocationIndex: editingAttackIndex }); return; } if (controlMode === "tap" && editingGoldAbilityId !== null) { submit({ type: "REMOVE_GOLD_PLACEMENT", abilityId: editingGoldAbilityId }); return; } if (model.phaseCta === "UNSELECT") { setSelectedIds([]); setTargetId(null); return; } const id = model.phaseCta === "ROLL" ? "roll" : model.phaseCta === "FINISH_BLUE" ? "finish-blue" : model.phaseCta === "RESOLVE_ASSIGNMENTS" ? "resolve" : null; const action = view.actions.find(entry => entry.id === id); if (action) submit(action.command); };
  const active = (id: string) => !!targetById(id);
  const tileDropProps = (id: string) => ({ onDragOver: (event: DragEvent) => { if (active(id)) event.preventDefault(); }, onDrop: (event: DragEvent) => drop(event, targetById(id)) });
  const moodStatus = view.mood.name ? `${view.mood.name}${view.mood.effect ? ` · ${view.mood.effect}` : ""}` : "No active Mood";
  const moodStatusVisible = view.mood.id !== null && view.mood.id !== "mood.ghost_pholus" && view.mood.id !== "mood.ghost_abderus";
  const abilityIdFor = (command: EngineCommand): string | null => {
    if (command.type === "USE_BLUE_ABILITY" || command.type === "REROLL_DIE" || command.type === "PLACE_GOLD") return command.abilityId;
    if (command.type === "USE_COWS_A") return "ability.reward.L05.A.blue";
    if (command.type === "USE_COWS_B") return "ability.reward.L05.B.blue";
    return null;
  };
  const faceForCommand = (command: EngineCommand): number | null => {
    if (command.type === "USE_COWS_A") return command.face;
    if (command.type !== "USE_BLUE_ABILITY" || command.target === undefined) return null;
    const projectedFace = view.actions.find(action => action.command === command)?.label.match(/→ (\d)$/)?.[1];
    if (projectedFace) return Number(projectedFace);
    if (command.abilityId !== "ability.bow.blue") return command.target >= 1 && command.target <= 6 ? command.target : null;
    const source = view.dice[command.sourceDieId];
    if (!source?.face) return null;
    return ((source.face - 1 + command.target + 6) % 6) + 1;
  };
  const pendingCowsFaceCommands = pendingCows?.abilityId === "ability.reward.L05.A.blue" && pendingCows.targetDieId ? view.actions.flatMap(action => action.command.type === "USE_COWS_A" && action.command.sourceDieId === pendingCows.sourceDieId && action.command.targetDieId === pendingCows.targetDieId ? [action.command] : []) : [];
  const actionCards = view.actionCards.map(card => ({ ...card, slots: card.slots.map(slot => {
    const target = card.disabled ? null : interactionTargets.find(candidate => candidate.commands.some(command => abilityIdFor(command) === slot.id)) ?? null;
    const goldPlacement = view.goldPlacements.find(candidate => candidate.abilityId === slot.id);
    const bluePlacement = view.bluePlacements.find(candidate => candidate.abilityId === slot.id);
    const provisionalCowsSource = pendingCows?.abilityId === slot.id ? pendingCows.sourceDieId : null;
    const placement = goldPlacement ? { kind: "gold" as const, ...goldPlacement } : bluePlacement ? { kind: "blue" as const, ...bluePlacement } : provisionalCowsSource ? { kind: "blue" as const, abilityId: slot.id, dieIds: [provisionalCowsSource], contributionIds: [] } : null;
    return { ...slot, target, placement, provisionalCowsSource };
  }) }));
  const decisionTitle = view.pendingDecision?.type === "CHOOSE_REWARD" ? "Choose a Reward" : view.pendingDecision?.prompt;
  const decisionActions = view.actions.filter(action => action.group === "decision");
  const rewardChoice = view.pendingDecision?.type === "CHOOSE_REWARD";
  const selectedDecision = decisionActions.find(action => action.id === selectedDecisionId) ?? null;
  const moodDecision = activePresentation?.kind === "mood" && view.pendingDecision?.source.kind === "mood" ? view.pendingDecision : null;
  const resolveAnywayDecision = view.pendingDecision?.type === "CONFIRM_RESOLVE_WITH_UNUSED_MEANINGFUL_PLACEMENT";
  const submitMoodDecision = (command: EngineCommand) => { dismissPresentation(); submit(command); };
  const activePreview = dragPreview ?? snapbackPreview;
  const previewPieces = activePreview?.pieceIds.map(id => {
    const die = view.dice[id] ?? view.derivedContributions.find(candidate => candidate.id === id);
    return { id, face: die?.face ?? null };
  }) ?? [];

  return <main className="gameplay-shell">
    <header className="status-strip"><div className="brand"><span>HERCULES</span><b>12 Labors</b></div><div className="resources" aria-label="Resources"><span title="Spirit">♥ <b>{view.player.spirit}</b></span><span title="Divinity">✦ <b>{view.player.divinity}</b></span></div><div className="labor-status"><small>Labor {laborNumeral(view.labor?.id)}</small><b>{view.labor?.name ?? "Preparing"}</b></div><div className="status-actions">{moodStatusVisible && <button className="mood-status" title={moodStatus} aria-label={`Current Mood: ${moodStatus}`} aria-haspopup="dialog" onClick={() => setMoodDetailsOpen(true)}>☾ <span>{moodCompact(view.mood.id)}</span></button>}<button className="menu-button" aria-label="Open game menu" aria-expanded={menuOpen} onClick={() => setMenuOpen(open => !open)}>☰</button></div></header>
    <section className="forecast-strip" aria-live="polite">{model.forecast.entries.map(entry => <span key={entry.id} className={`forecast-${entry.id}`}>{entry.id === "damage" ? "⚔" : entry.id === "heal" ? "✚" : entry.id === "spirit" ? "♥" : entry.id === "divinity" ? "✦" : entry.id === "break" ? "⬢" : entry.id === "defeat" ? "☠" : "↪"}{entry.value !== undefined && <> {entry.value > 0 && (entry.id === "heal" || entry.id === "spirit" || entry.id === "divinity") ? "+" : ""}{entry.value}</>} {entry.label}</span>)}{state.currentLabor?.cannotBlockThisRound && <span className="cannot-block">🛡̸ Cannot Block</span>}</section>
    {menuOpen && <aside className="game-menu" aria-label="Game menu"><label>Controls<select value={controlMode} onChange={event => { setControlMode(event.target.value as "drag" | "tap"); setSelectedIds([]); setTargetId(null); setEditingAttackIndex(null); setEditingGoldAbilityId(null); }}><option value="drag">Drag dice</option><option value="tap">Tap-select</option></select></label><label>Difficulty<select value={difficulty} onChange={event => setDifficulty(event.target.value as Difficulty)}>{(["human", "hero", "god"] as Difficulty[]).map(value => <option key={value}>{value}</option>)}</select></label><label>Seed<input value={seed} onChange={event => setSeed(event.target.value)} /></label><button onClick={() => start(seed)}>Start this seed</button><button onClick={() => start()}>New random game</button><button onClick={() => download("hercules-diagnostics.json", HerculesEngine.exportDiagnostics(state))}>Export diagnostics</button><button onClick={() => setDebug(value => !value)}>{debug ? "Hide" : "Show"} debug</button></aside>}
    <section ref={actionGridRef} className="action-grid" aria-label="Action grid">
      <article className={`labor-tile panes-${view.labor?.dice.length ?? 1}`}><div className="labor-tile-heading"><span>Labor</span></div><div className="labor-panes">{view.labor?.dice.map(die => { const id = `attack:${die.id}`; const legal = active(id); const assigned = state.round.attackAllocations.map((allocation, index) => ({ allocation, index })).filter(({ allocation }) => allocation.targetId === die.id || allocation.targetId === "__all_active_targets__"); return <div key={die.id} data-drop-target={legal ? id : undefined} className={`labor-pane ${legal ? "is-legal" : ""} ${die.status !== "active" ? "is-defeated" : ""}`} onClick={() => { if (controlMode === "tap") chooseLegalTarget(targetById(id)); }} {...tileDropProps(id)}><span>{die.label}</span><b>{die.health}/{die.startingHealth}</b><small>{die.attack}</small><em>Next: {die.upcomingEffects.join(" / ") || "No further effect."}</em>{assigned.length > 0 && <div className="attack-bundles">{assigned.map(({ allocation, index }) => <button key={index} draggable={controlMode === "drag"} className={`attack-bundle ${editingAttackIndex === index ? "is-editing" : ""} ${bundleDragging && editingAttackIndex === index ? "is-dragging" : ""}`} onDragStart={event => { if (controlMode !== "drag") return; event.dataTransfer.setData("application/x-hercules-attack-allocation", String(index)); event.dataTransfer.effectAllowed = "move"; setSelectedIds([]); setTargetId(null); setEditingGoldAbilityId(null); setEditingAttackIndex(index); }} onClick={event => { event.stopPropagation(); if (suppressBundleClick.current || selectedIds.length > 0) return; if (controlMode === "tap") { setSelectedIds([]); setTargetId(null); setEditingGoldAbilityId(null); setEditingAttackIndex(index); } else submit({ type: "REMOVE_ATTACK_ALLOCATION", allocationIndex: index }); }} onPointerDown={event => beginBundleTouchDrag(event, index)} onPointerMove={moveBundleTouchDrag} onPointerUp={endBundleTouchDrag} onPointerCancel={cancelBundleTouchDrag}>{[...allocation.dieIds, ...allocation.contributionIds].map(pieceId => <span key={pieceId} className="attack-bundle-die">{view.dice[pieceId]?.face ?? view.derivedContributions.find(candidate => candidate.id === pieceId)?.face ?? "—"}</span>)}</button>)}</div>}</div>; }) ?? <p>Labor is preparing…</p>}</div></article>
      {actionCards.map(card => { const cardTarget = card.slots.find(slot => slot.target)?.target ?? null; const cowsSlot = card.slots.find(slot => cowsAbility(slot.id)); const selectedSourceId = selectedIds.length === 1 ? selectedIds[0] : null; const armableCows = !pendingCows && !!cowsSlot && !!selectedSourceId && canArmCows(cowsSlot.id, selectedSourceId); const cowsDropId = !pendingCows && cowsSlot ? `blue:${cowsSlot.id}` : undefined; const dropTargetId = cardTarget?.id ?? cowsDropId; const cardDropProps = dropTargetId ? { onDragOver: (event: DragEvent) => event.preventDefault(), onDrop: (event: DragEvent) => { event.preventDefault(); const sourceId = event.dataTransfer.getData("application/x-hercules-tray-die"); if (cowsSlot && sourceId && canArmCows(cowsSlot.id, sourceId)) { armCows(cowsSlot.id, sourceId); return; } drop(event, cardTarget ?? undefined); }, onClick: () => { if (controlMode === "tap" && cowsSlot && selectedSourceId && armableCows) { armCows(cowsSlot.id, selectedSourceId); return; } if (controlMode === "tap") chooseLegalTarget(cardTarget); } } : {}; return <article key={card.id} data-drop-target={dropTargetId} className={`action-tile action-card ${card.slots.every(slot => slot.color === "blue") ? "blue" : "reward"} ${cardTarget || armableCows ? "is-legal" : ""} ${card.disabled ? "is-card-disabled" : ""}`} aria-label={card.name} {...cardDropProps}>
        <b>{card.name}</b><small>{card.summary}</small>
        <div className="action-slots" aria-label={`${card.name} ability slots`}>{card.slots.map(slot => {
          const placement = slot.placement;
          const goldPlacement = placement?.kind === "gold";
          const legal = !!slot.target;
          const placedIds = placement ? [...placement.dieIds, ...(goldPlacement ? placement.contributionIds : []), ...(placement.kind === "blue" ? parkedCopyIdsByAbility.get(placement.abilityId) ?? [] : [])] : [];
          const compactOccupied = !!placement && card.slots.some(other => other.id !== slot.id && other.color === slot.color && !other.placement);
          const targetableCowsDie = placement?.kind === "blue" && placedIds.length === 1 && cowsTargetIds.has(placedIds[0]);
          return <button key={slot.id} style={placedIds.length > 1 ? { "--placed-die-count": placedIds.length } as CSSProperties : undefined} className={`action-slot ${slot.color} ${placement ? "is-occupied" : ""} ${targetableCowsDie ? "is-targetable" : ""} ${placedIds.length > 1 ? "has-bundle" : ""} ${compactOccupied ? "is-compact-occupied" : ""} ${goldDragging && goldPlacement && placement.abilityId === editingGoldAbilityId ? "is-dragging" : ""}`} disabled={!legal && !placement} draggable={!!goldPlacement && controlMode === "drag"} title={goldPlacement ? controlMode === "tap" ? "Select this committed Gold placement" : "Tap to return this committed Gold placement, or drag it to a highlighted target" : targetableCowsDie ? "Choose this die" : placement ? "Used this Blue phase" : legal ? "Drag selected dice anywhere on this card" : `${slot.color === "blue" ? "Blue" : "Gold"} space`} onDragStart={goldPlacement ? event => { if (controlMode !== "drag") return; event.dataTransfer.setData("application/x-hercules-gold-placement", placement.abilityId); event.dataTransfer.effectAllowed = "move"; setSelectedIds([]); setTargetId(null); setEditingAttackIndex(null); setEditingGoldAbilityId(placement.abilityId); } : undefined} onClick={event => { event.stopPropagation(); if (targetableCowsDie) { chooseCowsTarget(placedIds[0]); return; } if (slot.provisionalCowsSource) { setPendingCows(null); return; } if (goldPlacement && !suppressGoldClick.current) { if (controlMode === "tap") { setSelectedIds([]); setTargetId(null); setEditingAttackIndex(null); setEditingGoldAbilityId(placement.abilityId); } else submit({ type: "REMOVE_GOLD_PLACEMENT", abilityId: placement.abilityId }); return; } if (controlMode === "tap") { if (cowsAbility(slot.id) && selectedSourceId && canArmCows(slot.id, selectedSourceId)) armCows(slot.id, selectedSourceId); else chooseLegalTarget(slot.target); } }} onPointerDown={goldPlacement ? event => beginGoldTouchDrag(event, placement.abilityId) : undefined} onPointerMove={goldPlacement ? moveGoldTouchDrag : undefined} onPointerUp={goldPlacement ? endGoldTouchDrag : undefined} onPointerCancel={goldPlacement ? cancelGoldTouchDrag : undefined}>
            <span className="action-slot-icon" aria-hidden="true">{slot.color === "blue" ? "◆" : "✦"}</span>
            {placedIds.length > 0 && <span className="placed-dice" aria-label={`${card.name} placement`}>{placedIds.map(id => <span key={id} className={id.includes("-D") ? "derived-die" : ""}>{view.dice[id]?.face ?? view.derivedContributions.find(candidate => candidate.id === id)?.face ?? "—"}</span>)}</span>}
          </button>;
        })}</div>
      </article>; })}
    </section>
    <section className="bottom-rail"><button className="undo-button" disabled={!model.undoAvailable} onClick={() => submit({ type: "UNDO_DETERMINISTIC" })}>↶<span>Undo</span></button><div className="dice-tray" aria-label="Hercules dice">{orderedTrayDice.map(die => { const derived = "sourceDieId" in die; const targetable = cowsTargetIds.has(die.id); return <Die key={die.id} id={die.id} face={die.face} selected={selectedIds.includes(die.id)} targetable={targetable} draggable={controlMode === "drag"} dragging={touchDragging && selectedIds.includes(die.id)} disabled={!phaseAllowsSelection || (!derived && (die.face === null || die.broken || die.spent))} state={derived ? `copy of ${die.sourceDieId}` : die.spent ? "spent" : die.blueUsed ? "blue used" : die.rollable ? "ready" : "unavailable"} onSelect={() => targetable ? chooseCowsTarget(die.id) : toggle(die.id)} onDragStart={event => beginDrag(event, die.id)} onDragOver={event => event.preventDefault()} onDrop={event => trayDrop(event, die.id)} onPointerDown={event => beginTouchDrag(event, die.id)} onPointerMove={moveTouchDrag} onPointerUp={endTouchDrag} onPointerCancel={cancelTouchDrag} />; })}</div><button className="phase-cta" disabled={!model.phaseCta && !(controlMode === "tap" && (editingAttackIndex !== null || editingGoldAbilityId !== null))} onClick={ctaAction}>{controlMode === "tap" && (editingAttackIndex !== null || editingGoldAbilityId !== null) ? "Return to tray" : model.phaseCta === "UNSELECT" ? "Unselect" : model.phaseCta === "FINISH_BLUE" ? "Finish Blue" : model.phaseCta === "RESOLVE_ASSIGNMENTS" ? "Resolve" : "Roll"}</button></section>
    {pendingCows?.targetDieId && <section className="choice-sheet cows-sheet" role="dialog" aria-label="100 Immortal Cows"><button className="choice-close" onClick={() => setPendingCows(null)}>×</button><h2>Set a die</h2><p>Choose its new face.</p><div className="face-picker">{pendingCowsFaceCommands.map(command => <button key={command.face} onClick={() => submit(command)} aria-label={`Set to ${command.face}`}><b>{command.face}</b></button>)}</div></section>}
    {selectedTarget && <section className="choice-sheet" role="dialog" aria-label={selectedTarget.label}><button className="choice-close" onClick={() => setTargetId(null)}>×</button><h2>{selectedTarget.label}</h2>{selectedTarget.commands.length > 0 && selectedTarget.commands.every(command => faceForCommand(command) !== null) ? <><p>Choose the resulting face.</p><div className="face-picker">{selectedTarget.commands.map((command, index) => <button key={index} onClick={() => submit(command)} aria-label={`Set to ${faceForCommand(command)}`}><b>{faceForCommand(command)}</b></button>)}</div></> : <><p>Choose the certified action for this selection.</p>{selectedTarget.commands.map((command, index) => <button key={index} onClick={() => submit(command)}>{command.type === "USE_COWS_B" ? `Reroll ${command.rerollDieIds.map(dieLabel).join(", ")}` : "Confirm placement"}</button>)}</>}</section>}
    {moodDetailsOpen && view.mood.name && <div className="mood-detail-backdrop" role="presentation" onClick={() => setMoodDetailsOpen(false)}><section className="presentation-card mood current-mood-card" role="dialog" aria-modal="true" aria-label="Current Mood" onClick={event => event.stopPropagation()}><button className="current-mood-close" aria-label="Close Current Mood" onClick={() => setMoodDetailsOpen(false)}>×</button><p>CURRENT MOOD</p><h1>{view.mood.name}</h1><strong>{view.mood.effect}</strong></section></div>}
    {activePresentation && !view.game.result && <section className={`presentation-card ${activePresentation.kind}`} role="dialog" aria-live="assertive" aria-label={activePresentation.title}><p>{activePresentation.eyebrow}</p><h1>{activePresentation.title}</h1><strong>{activePresentation.detail}</strong>{moodDecision ? <div className="presentation-actions">{decisionActions.map(action => <button key={action.id} className={action.command.type === "CHOOSE_OPTION" && action.command.optionId === "redraw" ? "presentation-redraw" : ""} onClick={() => submitMoodDecision(action.command)}>{action.command.type === "CHOOSE_OPTION" && action.command.optionId === "redraw" ? "Redraw Mood with Zeus' Disregard" : action.command.type === "CHOOSE_OPTION" && action.command.optionId === "keep" ? "Continue with this Mood" : action.label}</button>)}</div> : <button onClick={dismissPresentation}>Continue</button>}</section>}
    {view.pendingDecision && !moodDecision && <section className="choice-sheet decision-sheet" role="dialog" aria-label={decisionTitle}><h2>{resolveAnywayDecision ? "Unused meaningful placement" : decisionTitle}</h2><p>{resolveAnywayDecision ? "The engine found another placement that could still change this round. You may return to assignments or resolve anyway." : view.pendingDecision.prompt}</p>{decisionActions.map(action => <button key={action.id} className={rewardChoice && selectedDecisionId === action.id ? "is-selected-decision" : ""} onClick={() => rewardChoice ? setSelectedDecisionId(action.id) : submit(action.command)}>{resolveAnywayDecision && action.command.type === "CHOOSE_OPTION" && action.command.optionId === "return" ? "Return to assignments" : resolveAnywayDecision && action.command.type === "CHOOSE_OPTION" && action.command.optionId === "resolve_anyway" ? "Resolve anyway" : action.label}</button>)}{rewardChoice && <button disabled={!selectedDecision} onClick={() => selectedDecision && submit(selectedDecision.command)}>Confirm Reward</button>}</section>}
    {view.game.result && <section className={`end-state ${view.game.result}`} role="dialog"><p>{view.game.result === "victory" ? "HERCULES' ASCENSION" : "YOUR JOURNEY IS OVER"}</p><h1>{view.game.result === "victory" ? "VICTORY" : "You have failed."}</h1><strong>{view.game.result === "victory" ? "Cerberus is defeated. Hercules ascends." : state.player.spirit === "SKULL" ? "Spirit reached its failure space." : "A Labor die reached its final failure."}</strong><button onClick={() => start()}>New Game</button></section>}
    {debug && <section className="debug-panel"><h2>Canonical diagnostics</h2><pre>{JSON.stringify(HerculesEngine.exportDiagnostics(state), null, 2)}</pre></section>}
    {dragPreview && <div className="drag-preview" style={{ left: dragPreview.x, top: dragPreview.y }} aria-hidden="true">{previewPieces.map(piece => <span key={piece.id}><b>{piece.face ?? "—"}</b></span>)}</div>}
    {snapbackPreview && <div className={`drag-preview snapback-preview ${snapbackPreview.returning ? "is-returning" : ""}`} style={{ left: snapbackPreview.returning ? snapbackPreview.originX : snapbackPreview.x, top: snapbackPreview.returning ? snapbackPreview.originY : snapbackPreview.y, "--snapback-scale": snapbackPreview.returning ? 1 : snapbackPreview.startScale } as CSSProperties} aria-hidden="true">{previewPieces.map(piece => <span key={piece.id}><b>{piece.face ?? "—"}</b></span>)}</div>}
  </main>;
}

export { App };
