import { useEffect, useMemo, useRef, useState, type CSSProperties, type DragEvent, type PointerEvent } from "react";
import { HerculesEngine, type LegalTarget } from "../engine/api.js";
import type { EngineCommand } from "../engine/commands/types.js";
import type { Difficulty, GameState } from "../engine/state/types.js";
import { moodPresentation, presentationEventsFromTransitions, type GameplayPresentation } from "./presentation.js";
import "./playtest.css";

const SAVE_KEY = "hercules-12-labors.playtest.save.v1";
const TRAY_ORDER_KEY = "hercules-12-labors.playtest.tray-order.v1";
let fallbackSeedCounter = 0;
const randomSeed = (): string => { const values = new Uint32Array(2); if (globalThis.crypto?.getRandomValues) { globalThis.crypto.getRandomValues(values); return `playtest-${values[0].toString(36)}-${values[1].toString(36)}`; } fallbackSeedCounter += 1; return `playtest-${Date.now().toString(36)}-${fallbackSeedCounter.toString(36)}`; };
const freshGame = () => HerculesEngine.createGame({ difficulty: "human", seed: randomSeed() }).state;
const persistGame = (state: GameState): boolean => { try { window.localStorage.setItem(SAVE_KEY, JSON.stringify(HerculesEngine.serialize(state))); return true; } catch { return false; } };
const loadGame = (): { state: GameState; restored: boolean } => { try { const saved = window.localStorage.getItem(SAVE_KEY); return saved ? { state: HerculesEngine.deserialize(JSON.parse(saved)), restored: true } : { state: freshGame(), restored: false }; } catch { window.localStorage.removeItem(SAVE_KEY); return { state: freshGame(), restored: false }; } };
const loadTrayOrder = (): string[] => { try { const saved = JSON.parse(window.localStorage.getItem(TRAY_ORDER_KEY) ?? "[]"); return Array.isArray(saved) && saved.every(id => typeof id === "string") ? saved : []; } catch { return []; } };
const reconcileTrayOrder = (order: string[], knownIds: string[]) => { const known = new Set(knownIds); return [...order.filter(id => known.has(id)), ...knownIds.filter(id => !order.includes(id))]; };
const download = (name: string, value: unknown) => { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); };
const dieLabel = (id: string) => id.replace(/^labor\.L\d+\./, "").replace(/-D\d+$/, " copy");
type DragPreview = { pieceIds: string[]; x: number; y: number };

function Die({ id, face, selected, disabled, state, dragging, onSelect, onDragStart, onDragOver, onDrop, onPointerDown, onPointerMove, onPointerUp, onPointerCancel }: { id: string; face: number | null; selected: boolean; disabled: boolean; state: string; dragging: boolean; onSelect: () => void; onDragStart: (event: DragEvent<HTMLButtonElement>) => void; onDragOver: (event: DragEvent<HTMLButtonElement>) => void; onDrop: (event: DragEvent<HTMLButtonElement>) => void; onPointerDown: (event: PointerEvent<HTMLButtonElement>) => void; onPointerMove: (event: PointerEvent<HTMLButtonElement>) => void; onPointerUp: (event: PointerEvent<HTMLButtonElement>) => void; onPointerCancel: () => void }) {
  return <button data-tray-die={id} className={`die-tile ${selected ? "is-selected" : ""} ${dragging ? "is-dragging" : ""} ${disabled ? "is-disabled" : ""}`} style={{ touchAction: "none", userSelect: "none", opacity: dragging ? 0.68 : undefined, transform: dragging ? "scale(1.07)" : undefined }} disabled={disabled} draggable={!disabled} onClick={onSelect} onDragStart={onDragStart} onDragOver={onDragOver} onDrop={onDrop} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={onPointerCancel} aria-label={`${dieLabel(id)}, ${face ?? "unrolled"}, ${state}`}><strong>{face ?? "—"}</strong></button>;
}

function App() {
  const [loaded] = useState(loadGame);
  const [state, setState] = useState<GameState>(loaded.state);
  const [presentationQueue, setPresentationQueue] = useState<GameplayPresentation[]>([]);
  const seenTransitionCount = useRef(loaded.state.transitions.length);
  const needsInitialMoodPresentation = useRef(!loaded.restored);
  const [selectedDecisionId, setSelectedDecisionId] = useState<string | null>(null);
  const [difficulty, setDifficulty] = useState<Difficulty>(loaded.state.game.difficulty);
  const [seed, setSeed] = useState(loaded.state.rng.seed);
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [trayOrder, setTrayOrder] = useState<string[]>(loadTrayOrder);
  const [targetId, setTargetId] = useState<string | null>(null);
  const [editingAttackIndex, setEditingAttackIndex] = useState<number | null>(null);
  const [editingGoldAbilityId, setEditingGoldAbilityId] = useState<string | null>(null);
  const [touchDragging, setTouchDragging] = useState(false);
  const [bundleDragging, setBundleDragging] = useState(false);
  const [goldDragging, setGoldDragging] = useState(false);
  const [dragPreview, setDragPreview] = useState<DragPreview | null>(null);
  const actionGridRef = useRef<HTMLElement | null>(null);
  const touchGesture = useRef<{ pointerId: number; startX: number; startY: number; dieIds: string[]; moved: boolean } | null>(null);
  const bundleGesture = useRef<{ pointerId: number; startX: number; startY: number; allocationIndex: number; moved: boolean } | null>(null);
  const goldGesture = useRef<{ pointerId: number; startX: number; startY: number; abilityId: string; moved: boolean } | null>(null);
  const suppressTouchClick = useRef(false);
  const suppressBundleClick = useRef(false);
  const suppressGoldClick = useRef(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [debug, setDebug] = useState(false);
  const [message, setMessage] = useState("");
  const model = useMemo(() => HerculesEngine.getGameplayScreenModel(state, selectedIds), [state, selectedIds]);
  const { view } = model;
  const phaseAllowsSelection = view.game.phase === "BLUE_ABILITY_WINDOW" || view.game.phase === "GOLD_AND_ATTACK_PLACEMENT";
  // A die belongs to its committed attack or Gold tile, not as a disabled ghost in the tray.
  const physicalDice = Object.values(view.dice).filter(die => die.availableForLabor && !die.allocated && !die.locked && !(view.game.phase === "BLUE_ABILITY_WINDOW" && typeof die.placement === "object" && die.placement !== null && (die.placement as { kind?: string }).kind === "blue"));
  const trayDice = [...physicalDice, ...view.derivedContributions.filter(die => !die.allocated)];
  const trayDiceById = new Map(trayDice.map(die => [die.id, die]));
  const knownTrayIds = [...Object.keys(view.dice), ...view.derivedContributions.map(die => die.id)];
  const orderedTrayDice = reconcileTrayOrder(trayOrder, knownTrayIds).flatMap(id => { const die = trayDiceById.get(id); return die ? [die] : []; });
  const editableAttackTargets = useMemo(() => editingAttackIndex === null ? [] : HerculesEngine.getEditableAttackTargets(state, editingAttackIndex), [editingAttackIndex, state]);
  const editableGoldTargets = useMemo(() => editingGoldAbilityId === null ? [] : HerculesEngine.getEditableGoldTargets(state, editingGoldAbilityId), [editingGoldAbilityId, state]);
  const interactionTargets = editingAttackIndex !== null ? editableAttackTargets : editingGoldAbilityId !== null ? editableGoldTargets : model.legalTargets;
  const selectedTarget = interactionTargets.find(target => target.id === targetId) ?? null;
  const activePresentation = presentationQueue[0] ?? null;
  const targetById = (id: string) => interactionTargets.find(target => target.id === id);
  const dismissPresentation = () => setPresentationQueue(current => current.slice(1));
  const submit = (command: EngineCommand) => { try { const result = HerculesEngine.submit(state, command); if (command.type === "UNDO_DETERMINISTIC") setPresentationQueue([]); setState(result.state); persistGame(result.state); setSelectedIds([]); setTargetId(null); setEditingAttackIndex(null); setEditingGoldAbilityId(null); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } };
  const start = (nextSeed = randomSeed()) => { const next = HerculesEngine.createGame({ difficulty, seed: nextSeed }).state; const nextMood = HerculesEngine.getPlayView(next).mood; setSeed(nextSeed); seenTransitionCount.current = next.transitions.length; setState(next); setTrayOrder(Object.keys(next.herculesDice)); persistGame(next); setPresentationQueue(nextMood.id && nextMood.name ? [moodPresentation(`setup:${nextMood.id}`, nextMood.name, nextMood.effect)] : []); setSelectedDecisionId(null); setSelectedIds([]); setTargetId(null); setMessage(""); };
  useEffect(() => { persistGame(state); }, [state]);
  useEffect(() => { setTrayOrder(current => reconcileTrayOrder(current, knownTrayIds)); }, [knownTrayIds.join("|")]);
  useEffect(() => { try { window.localStorage.setItem(TRAY_ORDER_KEY, JSON.stringify(trayOrder)); } catch { /* Local ordering is optional. */ } }, [trayOrder]);
  useEffect(() => { if (!needsInitialMoodPresentation.current) return; needsInitialMoodPresentation.current = false; if (view.mood.id && view.mood.name) setPresentationQueue([moodPresentation(`setup:${view.mood.id}`, view.mood.name, view.mood.effect)]); }, [view.mood.effect, view.mood.id, view.mood.name]);
  useEffect(() => { const transitions = state.transitions.slice(seenTransitionCount.current); seenTransitionCount.current = state.transitions.length; const presentations = presentationEventsFromTransitions(transitions); if (presentations.length) setPresentationQueue(current => [...current, ...presentations]); }, [state.transitions]);
  useEffect(() => { setSelectedDecisionId(null); }, [view.pendingDecision?.id]);
  const toggle = (id: string) => { if (suppressTouchClick.current || !phaseAllowsSelection) return; setEditingAttackIndex(null); setEditingGoldAbilityId(null); setTargetId(null); setSelectedIds(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]); };
  const beginDrag = (event: DragEvent<HTMLButtonElement>, id: string) => { event.dataTransfer.setData("application/x-hercules-tray-die", id); event.dataTransfer.effectAllowed = "move"; if (!selectedIds.includes(id)) setSelectedIds([id]); setTargetId(null); };
  const reorderTrayDie = (sourceId: string, targetId: string) => { if (sourceId === targetId) return; setTrayOrder(current => { const order = reconcileTrayOrder(current, knownTrayIds); if (!order.includes(sourceId) || !order.includes(targetId)) return order; const withoutSource = order.filter(id => id !== sourceId); const targetIndex = withoutSource.indexOf(targetId); return [...withoutSource.slice(0, targetIndex), sourceId, ...withoutSource.slice(targetIndex)]; }); };
  const trayDrop = (event: DragEvent<HTMLButtonElement>, targetId: string) => { const sourceId = event.dataTransfer.getData("application/x-hercules-tray-die"); if (!sourceId) return; event.preventDefault(); reorderTrayDie(sourceId, targetId); };
  const drop = (event: DragEvent, target: LegalTarget | undefined) => { event.preventDefault(); const attackText = event.dataTransfer.getData("application/x-hercules-attack-allocation"); const allocationIndex = Number(attackText); if (Number.isInteger(allocationIndex) && attackText !== "") { const editableTarget = HerculesEngine.getEditableAttackTargets(state, allocationIndex).find(candidate => candidate.id === target?.id); if (editableTarget?.commands.length === 1) submit(editableTarget.commands[0]); return; } const goldAbilityId = event.dataTransfer.getData("application/x-hercules-gold-placement"); if (goldAbilityId) { const editableTarget = HerculesEngine.getEditableGoldTargets(state, goldAbilityId).find(candidate => candidate.id === target?.id); if (editableTarget?.commands.length === 1) submit(editableTarget.commands[0]); return; } if (!target) return; if (target.commands.length === 1) submit(target.commands[0]); else setTargetId(target.id); };
  const beginTouchDrag = (event: PointerEvent<HTMLButtonElement>, id: string) => { if (event.pointerType !== "touch" || !phaseAllowsSelection) return; touchGesture.current = { pointerId: event.pointerId, startX: event.clientX, startY: event.clientY, dieIds: selectedIds.includes(id) && selectedIds.length > 1 ? selectedIds : [id], moved: false }; event.currentTarget.setPointerCapture(event.pointerId); };
  const autoScrollGameplay = (clientY: number) => { const grid = actionGridRef.current; if (!grid) return; const bounds = grid.getBoundingClientRect(); const edge = 70; if (clientY < bounds.top + edge) grid.scrollTop -= Math.ceil((bounds.top + edge - clientY) / 5); else if (clientY > bounds.bottom - edge) grid.scrollTop += Math.ceil((clientY - (bounds.bottom - edge)) / 5); };
  const moveTouchDrag = (event: PointerEvent<HTMLButtonElement>) => { const gesture = touchGesture.current; if (!gesture || gesture.pointerId !== event.pointerId || event.pointerType !== "touch") return; if (!gesture.moved && Math.hypot(event.clientX - gesture.startX, event.clientY - gesture.startY) > 8) { gesture.moved = true; setSelectedIds(gesture.dieIds); setTargetId(null); setTouchDragging(true); } if (gesture.moved) { setDragPreview({ pieceIds: gesture.dieIds, x: event.clientX, y: event.clientY }); autoScrollGameplay(event.clientY); } };
  const endTouchDrag = (event: PointerEvent<HTMLButtonElement>) => { const gesture = touchGesture.current; if (!gesture || gesture.pointerId !== event.pointerId || event.pointerType !== "touch") return; touchGesture.current = null; setTouchDragging(false); setDragPreview(null); if (!gesture.moved) return; suppressTouchClick.current = true; window.setTimeout(() => { suppressTouchClick.current = false; }, 0); const sourceId = gesture.dieIds.length === 1 ? gesture.dieIds[0] : null; const trayTargetId = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-tray-die]")?.dataset.trayDie; if (sourceId && trayTargetId && sourceId !== trayTargetId) { reorderTrayDie(sourceId, trayTargetId); setSelectedIds([sourceId]); return; } const dropId = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-drop-target]")?.dataset.dropTarget; const target = HerculesEngine.getLegalTargets(state, gesture.dieIds).find(candidate => candidate.id === dropId); if (!target) { setSelectedIds(gesture.dieIds); return; } if (target.commands.length === 1) submit(target.commands[0]); else { setSelectedIds(gesture.dieIds); setTargetId(target.id); } };
  const cancelTouchDrag = () => { touchGesture.current = null; setTouchDragging(false); setDragPreview(null); };
  const beginBundleTouchDrag = (event: PointerEvent<HTMLButtonElement>, allocationIndex: number) => { if (event.pointerType !== "touch") return; bundleGesture.current = { pointerId: event.pointerId, startX: event.clientX, startY: event.clientY, allocationIndex, moved: false }; event.currentTarget.setPointerCapture(event.pointerId); };
  const moveBundleTouchDrag = (event: PointerEvent<HTMLButtonElement>) => { const gesture = bundleGesture.current; if (!gesture || gesture.pointerId !== event.pointerId || event.pointerType !== "touch") return; const allocation = state.round.attackAllocations[gesture.allocationIndex]; if (!gesture.moved && Math.hypot(event.clientX - gesture.startX, event.clientY - gesture.startY) > 8) { gesture.moved = true; setSelectedIds([]); setTargetId(null); setEditingAttackIndex(gesture.allocationIndex); setBundleDragging(true); } if (gesture.moved) { setDragPreview({ pieceIds: allocation ? [...allocation.dieIds, ...allocation.contributionIds] : [], x: event.clientX, y: event.clientY }); autoScrollGameplay(event.clientY); } };
  const endBundleTouchDrag = (event: PointerEvent<HTMLButtonElement>) => { const gesture = bundleGesture.current; if (!gesture || gesture.pointerId !== event.pointerId || event.pointerType !== "touch") return; bundleGesture.current = null; setBundleDragging(false); setDragPreview(null); suppressBundleClick.current = true; window.setTimeout(() => { suppressBundleClick.current = false; }, 0); if (!gesture.moved) { submit({ type: "REMOVE_ATTACK_ALLOCATION", allocationIndex: gesture.allocationIndex }); return; } const dropId = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-drop-target]")?.dataset.dropTarget; const target = HerculesEngine.getEditableAttackTargets(state, gesture.allocationIndex).find(candidate => candidate.id === dropId); if (target?.commands.length === 1) submit(target.commands[0]); else { setEditingAttackIndex(null); setMessage("That bundle cannot move there."); } };
  const cancelBundleTouchDrag = () => { bundleGesture.current = null; setBundleDragging(false); setDragPreview(null); };
  const beginGoldTouchDrag = (event: PointerEvent<HTMLButtonElement>, abilityId: string) => { if (event.pointerType !== "touch") return; goldGesture.current = { pointerId: event.pointerId, startX: event.clientX, startY: event.clientY, abilityId, moved: false }; event.currentTarget.setPointerCapture(event.pointerId); };
  const moveGoldTouchDrag = (event: PointerEvent<HTMLButtonElement>) => { const gesture = goldGesture.current; if (!gesture || gesture.pointerId !== event.pointerId || event.pointerType !== "touch") return; const placement = state.round.goldPlacements.find(candidate => candidate.abilityId === gesture.abilityId); if (!gesture.moved && Math.hypot(event.clientX - gesture.startX, event.clientY - gesture.startY) > 8) { gesture.moved = true; setSelectedIds([]); setTargetId(null); setEditingGoldAbilityId(gesture.abilityId); setGoldDragging(true); } if (gesture.moved) { setDragPreview({ pieceIds: placement ? [...placement.dieIds, ...placement.contributionIds] : [], x: event.clientX, y: event.clientY }); autoScrollGameplay(event.clientY); } };
  const endGoldTouchDrag = (event: PointerEvent<HTMLButtonElement>) => { const gesture = goldGesture.current; if (!gesture || gesture.pointerId !== event.pointerId || event.pointerType !== "touch") return; goldGesture.current = null; setGoldDragging(false); setDragPreview(null); suppressGoldClick.current = true; window.setTimeout(() => { suppressGoldClick.current = false; }, 0); if (!gesture.moved) { submit({ type: "REMOVE_GOLD_PLACEMENT", abilityId: gesture.abilityId }); return; } const dropId = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-drop-target]")?.dataset.dropTarget; const target = HerculesEngine.getEditableGoldTargets(state, gesture.abilityId).find(candidate => candidate.id === dropId); if (target?.commands.length === 1) submit(target.commands[0]); else { setEditingGoldAbilityId(null); setMessage("That Gold bundle cannot move there."); } };
  const cancelGoldTouchDrag = () => { goldGesture.current = null; setGoldDragging(false); setDragPreview(null); };
  const ctaAction = () => { if (model.phaseCta === "UNSELECT") { setSelectedIds([]); setTargetId(null); return; } const id = model.phaseCta === "ROLL" ? "roll" : model.phaseCta === "FINISH_BLUE" ? "finish-blue" : model.phaseCta === "RESOLVE_ASSIGNMENTS" ? "resolve" : null; const action = view.actions.find(entry => entry.id === id); if (action) submit(action.command); };
  const active = (id: string) => !!targetById(id);
  const tileDropProps = (id: string) => ({ onDragOver: (event: DragEvent) => { if (active(id)) event.preventDefault(); }, onDrop: (event: DragEvent) => drop(event, targetById(id)) });
  const moodStatus = view.mood.name ? `${view.mood.name}${view.mood.effect ? ` · ${view.mood.effect}` : ""}` : "No active Mood";
  const abilityIdFor = (command: EngineCommand): string | null => {
    if (command.type === "USE_BLUE_ABILITY" || command.type === "REROLL_DIE" || command.type === "PLACE_GOLD") return command.abilityId;
    if (command.type === "USE_COWS_A") return "ability.reward.L05.A.blue";
    if (command.type === "USE_COWS_B") return "ability.reward.L05.B.blue";
    return null;
  };
  const actionCards = view.actionCards.map(card => ({ ...card, slots: card.slots.map(slot => {
    const target = card.disabled ? null : interactionTargets.find(candidate => candidate.commands.some(command => abilityIdFor(command) === slot.id)) ?? null;
    const goldPlacement = view.goldPlacements.find(candidate => candidate.abilityId === slot.id);
    const bluePlacement = view.bluePlacements.find(candidate => candidate.abilityId === slot.id);
    const placement = goldPlacement ? { kind: "gold" as const, ...goldPlacement } : bluePlacement ? { kind: "blue" as const, ...bluePlacement } : null;
    return { ...slot, target, placement };
  }) }));
  const decisionTitle = view.pendingDecision?.type === "CHOOSE_REWARD" ? "Choose a Reward" : view.pendingDecision?.prompt;
  const decisionActions = view.actions.filter(action => action.group === "decision");
  const rewardChoice = view.pendingDecision?.type === "CHOOSE_REWARD";
  const selectedDecision = decisionActions.find(action => action.id === selectedDecisionId) ?? null;
  const moodDecision = activePresentation?.kind === "mood" && view.pendingDecision?.source.kind === "mood" ? view.pendingDecision : null;
  const resolveAnywayDecision = view.pendingDecision?.type === "CONFIRM_RESOLVE_WITH_UNUSED_MEANINGFUL_PLACEMENT";
  const submitMoodDecision = (command: EngineCommand) => { dismissPresentation(); submit(command); };
  const previewPieces = dragPreview?.pieceIds.map(id => {
    const die = view.dice[id] ?? view.derivedContributions.find(candidate => candidate.id === id);
    return { id, face: die?.face ?? null };
  }) ?? [];

  return <main className="gameplay-shell">
    <header className="status-strip"><div className="brand"><span>HERCULES</span><b>12 Labors</b></div><div className="resources" aria-label="Resources"><span title="Spirit">♥ <b>{view.player.spirit}</b></span><span title="Divinity">✦ <b>{view.player.divinity}</b></span></div><div className="labor-status"><small>Labor {view.labor?.id.match(/\d+/)?.[0] ?? "—"}</small><b>{view.labor?.name ?? "Preparing"}</b></div><button className="mood-status" title={moodStatus} aria-label={moodStatus}>☾</button><button className="menu-button" aria-label="Open game menu" aria-expanded={menuOpen} onClick={() => setMenuOpen(open => !open)}>☰</button></header>
    {(!model.forecast.neutral || state.currentLabor?.cannotBlockThisRound) && <section className="forecast-strip" aria-live="polite">{model.forecast.entries.map(entry => <span key={entry.id}>{entry.id === "attack" ? "⚔" : entry.id === "block" ? "🛡" : entry.id === "spirit" ? "♥" : "✦"} {entry.value > 0 && entry.id !== "attack" ? "+" : ""}{entry.value} {entry.label}</span>)}{state.currentLabor?.cannotBlockThisRound && <span className="cannot-block">🛡̸ Cannot Block</span>}</section>}
    {menuOpen && <aside className="game-menu" aria-label="Game menu"><label>Difficulty<select value={difficulty} onChange={event => setDifficulty(event.target.value as Difficulty)}>{(["human", "hero", "god"] as Difficulty[]).map(value => <option key={value}>{value}</option>)}</select></label><label>Seed<input value={seed} onChange={event => setSeed(event.target.value)} /></label><button onClick={() => start(seed)}>Start this seed</button><button onClick={() => start()}>New random game</button><button onClick={() => download("hercules-diagnostics.json", HerculesEngine.exportDiagnostics(state))}>Export diagnostics</button><button onClick={() => setDebug(value => !value)}>{debug ? "Hide" : "Show"} debug</button></aside>}
    {message && <p className="game-message" role="status">{message}</p>}
    <section ref={actionGridRef} className="action-grid" aria-label="Action grid">
      <article className={`labor-tile panes-${view.labor?.dice.length ?? 1}`}><div className="labor-tile-heading"><span>Labor</span></div><div className="labor-panes">{view.labor?.dice.map(die => { const id = `attack:${die.id}`; const legal = active(id); const assigned = state.round.attackAllocations.map((allocation, index) => ({ allocation, index })).filter(({ allocation }) => allocation.targetId === die.id || allocation.targetId === "__all_active_targets__"); return <div key={die.id} data-drop-target={legal ? id : undefined} className={`labor-pane ${legal ? "is-legal" : ""} ${die.status !== "active" ? "is-defeated" : ""}`} {...tileDropProps(id)}><span>{dieLabel(die.id)}</span><b>{die.health}/{die.startingHealth}</b><small>{die.attack}</small>{assigned.length > 0 && <div className="attack-bundles">{assigned.map(({ allocation, index }) => <button key={index} draggable className={`attack-bundle ${editingAttackIndex === index ? "is-editing" : ""} ${bundleDragging && editingAttackIndex === index ? "is-dragging" : ""}`} onDragStart={event => { event.dataTransfer.setData("application/x-hercules-attack-allocation", String(index)); event.dataTransfer.effectAllowed = "move"; setSelectedIds([]); setTargetId(null); setEditingGoldAbilityId(null); setEditingAttackIndex(index); }} onClick={event => { event.stopPropagation(); if (!suppressBundleClick.current) submit({ type: "REMOVE_ATTACK_ALLOCATION", allocationIndex: index }); }} onPointerDown={event => beginBundleTouchDrag(event, index)} onPointerMove={moveBundleTouchDrag} onPointerUp={endBundleTouchDrag} onPointerCancel={cancelBundleTouchDrag}>{[...allocation.dieIds, ...allocation.contributionIds].map(pieceId => <span key={pieceId} className="attack-bundle-die">{view.dice[pieceId]?.face ?? view.derivedContributions.find(candidate => candidate.id === pieceId)?.face ?? "—"}</span>)}</button>)}</div>}</div>; }) ?? <p>Labor is preparing…</p>}</div></article>
      {actionCards.map(card => { const cardTarget = card.slots.find(slot => slot.target)?.target ?? null; return <article key={card.id} data-drop-target={cardTarget?.id} className={`action-tile action-card ${card.slots.every(slot => slot.color === "blue") ? "blue" : "reward"} ${cardTarget ? "is-legal" : ""} ${card.disabled ? "is-card-disabled" : ""}`} aria-label={card.name} {...(cardTarget ? tileDropProps(cardTarget.id) : {})}>
        <span className="ability-square">{card.slots.some(slot => slot.color === "blue") ? "◆" : "✦"}</span><b>{card.name}</b><small>{card.summary}</small>
        <div className="action-slots" aria-label={`${card.name} ability slots`}>{card.slots.map(slot => {
          const placement = slot.placement;
          const goldPlacement = placement?.kind === "gold";
          const legal = !!slot.target;
          const placedIds = placement ? [...placement.dieIds, ...(goldPlacement ? placement.contributionIds : [])] : [];
          const compactOccupied = !!placement && card.slots.some(other => other.id !== slot.id && other.color === slot.color && !other.placement);
          return <button key={slot.id} style={placedIds.length > 1 ? { "--placed-die-count": placedIds.length } as CSSProperties : undefined} className={`action-slot ${slot.color} ${placement ? "is-occupied" : ""} ${placedIds.length > 1 ? "has-bundle" : ""} ${compactOccupied ? "is-compact-occupied" : ""} ${goldDragging && goldPlacement && placement.abilityId === editingGoldAbilityId ? "is-dragging" : ""}`} disabled={!legal && !placement} draggable={goldPlacement} title={goldPlacement ? "Tap to return this committed Gold placement, or drag it to a highlighted target" : placement ? "Used this Blue phase" : legal ? "Drag selected dice anywhere on this card" : `${slot.color === "blue" ? "Blue" : "Gold"} space`} onDragStart={goldPlacement ? event => { event.dataTransfer.setData("application/x-hercules-gold-placement", placement.abilityId); event.dataTransfer.effectAllowed = "move"; setSelectedIds([]); setTargetId(null); setEditingAttackIndex(null); setEditingGoldAbilityId(placement.abilityId); } : undefined} onClick={() => { if (goldPlacement && !suppressGoldClick.current) submit({ type: "REMOVE_GOLD_PLACEMENT", abilityId: placement.abilityId }); }} onPointerDown={goldPlacement ? event => beginGoldTouchDrag(event, placement.abilityId) : undefined} onPointerMove={goldPlacement ? moveGoldTouchDrag : undefined} onPointerUp={goldPlacement ? endGoldTouchDrag : undefined} onPointerCancel={goldPlacement ? cancelGoldTouchDrag : undefined}>
            <span className="action-slot-icon" aria-hidden="true">{slot.color === "blue" ? "◆" : "✦"}</span>
            {placedIds.length > 0 && <span className="placed-dice" aria-label={`${card.name} placement`}>{placedIds.map(id => <span key={id} className={id.includes("-D") ? "derived-die" : ""}>{view.dice[id]?.face ?? view.derivedContributions.find(candidate => candidate.id === id)?.face ?? "—"}</span>)}</span>}
          </button>;
        })}</div>
      </article>; })}
    </section>
    <section className="bottom-rail"><button className="undo-button" disabled={!model.undoAvailable} onClick={() => submit({ type: "UNDO_DETERMINISTIC" })}>↶<span>Undo</span></button><div className="dice-tray" aria-label="Hercules dice">{orderedTrayDice.map(die => { const derived = "sourceDieId" in die; return <Die key={die.id} id={die.id} face={die.face} selected={selectedIds.includes(die.id)} dragging={touchDragging && selectedIds.includes(die.id)} disabled={!phaseAllowsSelection || (!derived && (die.face === null || die.broken || die.spent))} state={derived ? `copy of ${die.sourceDieId}` : die.spent ? "spent" : die.blueUsed ? "blue used" : die.rollable ? "ready" : "unavailable"} onSelect={() => toggle(die.id)} onDragStart={event => beginDrag(event, die.id)} onDragOver={event => event.preventDefault()} onDrop={event => trayDrop(event, die.id)} onPointerDown={event => beginTouchDrag(event, die.id)} onPointerMove={moveTouchDrag} onPointerUp={endTouchDrag} onPointerCancel={cancelTouchDrag} />; })}</div><button className="phase-cta" disabled={!model.phaseCta} onClick={ctaAction}>{model.phaseCta === "UNSELECT" ? "Unselect" : model.phaseCta === "FINISH_BLUE" ? "Finish Blue" : model.phaseCta === "RESOLVE_ASSIGNMENTS" ? "Resolve" : "Roll"}</button></section>
    {selectedTarget && <section className="choice-sheet" role="dialog" aria-label={selectedTarget.label}><button className="choice-close" onClick={() => setTargetId(null)}>×</button><h2>{selectedTarget.label}</h2><p>Choose the certified action for this selection.</p>{selectedTarget.commands.map((command, index) => <button key={index} onClick={() => submit(command)}>{command.type === "USE_BLUE_ABILITY" && command.abilityId === "ability.bow.blue" ? `${command.target === -1 ? "Decrease" : "Increase"} ${dieLabel(command.sourceDieId)} by 1` : command.type === "USE_BLUE_ABILITY" && command.target !== undefined ? `Set to ${command.target}` : command.type === "USE_COWS_A" ? `Set ${dieLabel(command.targetDieId)} to ${command.face}` : command.type === "USE_COWS_B" ? `Reroll ${command.rerollDieIds.map(dieLabel).join(", ")}` : "Confirm placement"}</button>)}</section>}
    {activePresentation && !view.game.result && <section className={`presentation-card ${activePresentation.kind}`} role="dialog" aria-live="assertive" aria-label={activePresentation.title}><p>{activePresentation.eyebrow}</p><h1>{activePresentation.title}</h1><strong>{activePresentation.detail}</strong>{moodDecision ? <div className="presentation-actions">{decisionActions.map(action => <button key={action.id} className={action.command.type === "CHOOSE_OPTION" && action.command.optionId === "redraw" ? "presentation-redraw" : ""} onClick={() => submitMoodDecision(action.command)}>{action.command.type === "CHOOSE_OPTION" && action.command.optionId === "redraw" ? "Redraw Mood with Zeus' Disregard" : action.command.type === "CHOOSE_OPTION" && action.command.optionId === "keep" ? "Continue with this Mood" : action.label}</button>)}</div> : <button onClick={dismissPresentation}>Continue</button>}</section>}
    {view.pendingDecision && !moodDecision && <section className="choice-sheet decision-sheet" role="dialog" aria-label={decisionTitle}><h2>{resolveAnywayDecision ? "Unused meaningful placement" : decisionTitle}</h2><p>{resolveAnywayDecision ? "The engine found another placement that could still change this round. You may return to assignments or resolve anyway." : view.pendingDecision.prompt}</p>{decisionActions.map(action => <button key={action.id} className={rewardChoice && selectedDecisionId === action.id ? "is-selected-decision" : ""} onClick={() => rewardChoice ? setSelectedDecisionId(action.id) : submit(action.command)}>{resolveAnywayDecision && action.command.type === "CHOOSE_OPTION" && action.command.optionId === "return" ? "Return to assignments" : resolveAnywayDecision && action.command.type === "CHOOSE_OPTION" && action.command.optionId === "resolve_anyway" ? "Resolve anyway" : action.label}</button>)}{rewardChoice && <button disabled={!selectedDecision} onClick={() => selectedDecision && submit(selectedDecision.command)}>Confirm Reward</button>}</section>}
    {view.game.result && <section className={`end-state ${view.game.result}`} role="dialog"><p>{view.game.result === "victory" ? "HERCULES' ASCENSION" : "YOUR JOURNEY IS OVER"}</p><h1>{view.game.result === "victory" ? "VICTORY" : "You have failed."}</h1><strong>{view.game.result === "victory" ? "Cerberus is defeated. Hercules ascends." : state.player.spirit === "SKULL" ? "Spirit reached its failure space." : "A Labor die reached its final failure."}</strong><button onClick={() => start()}>New Game</button></section>}
    {debug && <section className="debug-panel"><h2>Canonical diagnostics</h2><pre>{JSON.stringify(HerculesEngine.exportDiagnostics(state), null, 2)}</pre></section>}
    {dragPreview && <div className="drag-preview" style={{ left: dragPreview.x, top: dragPreview.y }} aria-hidden="true">{previewPieces.map(piece => <span key={piece.id}><b>{piece.face ?? "—"}</b></span>)}</div>}
  </main>;
}

export { App };
