export type Difficulty = "human" | "hero" | "god";
export type GamePhase = "LABOR_SETUP" | "MOOD_RESOLUTION" | "READY_TO_ROLL" | "ROLL_COMMITTED" | "POST_ROLL_TRIGGERS" | "BLUE_ABILITY_WINDOW" | "GOLD_AND_ATTACK_PLACEMENT" | "DAMAGE_RESOLUTION" | "LABOR_DEFEAT_CHECK" | "LABOR_ADVANCE" | "IMPACT_RESOLUTION" | "FAILURE_CHECK" | "ROUND_CLEANUP" | "REWARD_SELECTION" | "LABOR_TRANSITION" | "VICTORY" | "DEFEAT";
export type PendingDecisionType = "CHOOSE_GHOST_ABDERUS_COST" | "CHOOSE_PHOLUS_REWARD" | "CHOOSE_BLUE_ABILITY" | "CHOOSE_REROLL_TARGET" | "FINISH_BLUE_PHASE" | "CHOOSE_GOLD_PLACEMENT" | "CHOOSE_ATTACK_ALLOCATION" | "CHOOSE_DAMAGE_DISTRIBUTION" | "RESOLVE_ASSIGNMENTS" | "CONFIRM_RESOLVE_WITH_UNUSED_MEANINGFUL_PLACEMENT" | "CHOOSE_TRACK_BRANCH" | "CHOOSE_DIE_TO_BREAK" | "CHOOSE_REWARD" | "CHOOSE_REWARD_TO_REMOVE" | "CHOOSE_ZEUS_REDRAW" | "CHOOSE_HIND_FAILURE_SELECTION";

export type HerculesDiePoolSource = "base" | "temporary_gain" | "temporarily_unavailable";
export interface HerculesDieState { id: string; face: number | null; rollable: boolean; blueUsed: boolean; spent: boolean; locked: boolean; allocated: boolean; broken: boolean; availableForLabor: boolean; poolSource: HerculesDiePoolSource; placement: unknown | null; history: unknown[]; }
export interface LaborDieState { id: string; health: number; startingHealth: number; trackId: string; nodeId: string; status: "active" | "defeated_inactive" | "active_failure_terminal"; }
export interface PendingDecision { id: string; type: PendingDecisionType; prompt: string; legalOptions: Array<{ id: string; label?: string; value?: unknown }>; source: { id: string; kind: string }; context: Record<string, unknown>; allowSkip: boolean; randomnessOnResolve: boolean; revealsHiddenInformation: boolean; undoBarrierOnResolve: boolean; }
export interface RngEventRecord { eventIndex: string; purpose: string; attempt: number; raw64?: string; result: unknown; status: "committed" | "orphaned_execution_error"; error?: string; }
export interface TransitionHistoryRecord { index: number; type: string; source: { kind: string; id: string }; payload: Record<string, unknown>; beforeHash: string; afterHash: string; }
export interface DeterministicUndoCheckpoint { rngNextEvent: string; state: Omit<GameState, "undoStack">; }
export interface DerivedContribution { id: string; sourceDieId: string; face: number; allocated: boolean; }
export interface AttackAllocation { targetId: string; dieIds: string[]; contributionIds: string[]; damage: number; }
export interface GoldPlacement { abilityId: string; dieIds: string[]; }
export interface GameState { schemaVersion: string; dataRevision: string; game: { difficulty: Difficulty; currentLaborId: string | null; completedLaborIds: string[]; phase: GamePhase; result: null | "victory" | "defeat" }; player: { spirit: number | "X" | "SKULL"; divinity: number | "X" | "TOP"; ownedRewardIds: string[]; removedRewardOrComponentIds: string[]; temporaryEffects: unknown[]; persistentHerculesDice: number }; herculesDice: Record<string, HerculesDieState>; currentLabor: { laborId: string; laborDice: Record<string, LaborDieState>; cannotBlockThisRound: boolean } | null; round: { rollNumber: number; rerollNumber: number; cowsBRerollNumber: number; effectiveDoubleDieIds: string[]; derivedContributions: Record<string, DerivedContribution>; goldPlacements: GoldPlacement[]; attackAllocations: AttackAllocation[]; blockedSpirit: number; resourceQueue: { spiritDeltas: number[]; divinityDeltas: number[] } }; mood: { deck: string[]; activeMoodId: string | null; returnedMoodIds: string[] }; rng: { algorithm: "SHA256_COUNTER_V1"; policyVersion: "HERC-RNG-v3"; seed: string; nextEvent: string; ledger: RngEventRecord[] }; pendingDecision: PendingDecision | null; pendingTriggers: unknown[]; transitionIndex: number; transitions: TransitionHistoryRecord[]; undoStack: DeterministicUndoCheckpoint[]; }
export interface SerializedGame { schemaVersion: string; dataRevision: string; contentHash: string; buildVersion: string; state: GameState; }
