import { GAME_DATA } from "../../data/generated/game-data.js";

type AnyRecord = Record<string, unknown>;
export interface RuntimeNode { id: string; effect: AnyRecord | null; next: string[]; }
export interface RuntimeTrack { id: string; type: string; startId: string; nodes: Record<string, RuntimeNode>; }

export function getLabor(laborId: string): AnyRecord { const labor = GAME_DATA.labors.find((entry) => entry.id === laborId); if (!labor) throw new Error(`Unknown Labor ${laborId}.`); return labor as unknown as AnyRecord; }
/** Compiles ordered linear data into explicit graph edges; all other graph adjacency stays source-defined. */
export function getTracks(laborId: string): Record<string, RuntimeTrack> { const labor = getLabor(laborId); const tracks = labor.tracks as Record<string, AnyRecord>; return Object.fromEntries(Object.entries(tracks).map(([id, track]) => { const raw = track.nodes as AnyRecord[] | Record<string, AnyRecord>; const ordered = Array.isArray(raw) ? raw.map((node) => [node.id as string, node] as const) : Object.entries(raw); const nodes = Object.fromEntries(ordered.map(([nodeId, node], index) => { const sourceNext = node.next as string[] | undefined; const next = sourceNext ?? (track.type === "linear" && index < ordered.length - 1 ? [ordered[index + 1][0]] : []); return [nodeId, { id: nodeId, effect: (node.effect as AnyRecord | null) ?? null, next }]; })); const startId = (track.start as string | undefined) ?? ordered[0]?.[0]; if (!startId) throw new Error(`Track ${id} has no start node.`); return [id, { id, type: track.type as string, startId, nodes }]; })); }
export function getNode(laborId: string, trackId: string, nodeId: string): RuntimeNode { const node = getTracks(laborId)[trackId]?.nodes[nodeId]; if (!node) throw new Error(`Unknown node ${nodeId} on track ${trackId}.`); return node; }
export function laborDice(laborId: string): Array<AnyRecord & { track_id: string; entry: string }> { const labor = getLabor(laborId); const tracks = getTracks(laborId); const soleTrack = Object.keys(tracks).length === 1 ? Object.keys(tracks)[0] : undefined; return ((labor.labor_dice as AnyRecord[] | undefined) ?? []).map((die) => { const trackId = (die.track_id as string | undefined) ?? soleTrack; if (!trackId) throw new Error(`Labor die ${String(die.id)} has no unambiguous track.`); const entry = (die.entry as string | undefined) ?? tracks[trackId].startId; return { ...die, track_id: trackId, entry }; }); }
