import { raw64 } from "../rng/herc-rng.js";
import { GAME_DATA } from "../data/generated/game-data.js";
import { allocateAttack, placeGoldAbility, useBlueAbility, useCowsB, useRerollOne } from "../engine/actions/placement.js";
import { chooseBrokenDie } from "../engine/decisions/resolve.js";
import { completeLaborTransition, completeLaborTransitionWithCheckpoint } from "../engine/labor/transition.js";
import { resolveAssignments } from "../engine/commands/resolve-assignments.js";
import { chooseReward, chooseRewardToRemove } from "../engine/rewards/resolve.js";
import { initializeGame } from "../engine/state/create.js";
import type { GameState } from "../engine/state/types.js";
import { resolveRoundDamage, rollFromRng } from "../engine/round/resolve.js";

type GoldenEvent = { event_index: number; status: string; purpose: string | null; attempt: number | null; raw64: string | null; interpreted_result?: { face?: number; j?: number }; };
export interface GoldenRunRecord { seed: string; rng_event_ledger: GoldenEvent[]; reproducibility: { status: string }; }
export interface ReplayVerification { passed: boolean; eventCount: number; orphanedEventCount: number; errors: string[]; }
/** Recomputes the supplied Golden Run ledger. Tactical replay is deliberately separate from ledger certification. */
export function verifyGoldenRunLedger(record: GoldenRunRecord): ReplayVerification { const errors: string[] = []; let orphaned = 0; for (const event of record.rng_event_ledger) { if (event.status === "orphaned_execution_error") { orphaned += 1; if (event.purpose !== null || event.raw64 !== null) errors.push(`event ${event.event_index}: orphaned event has random material`); continue; } if (!event.purpose || event.raw64 === null || event.attempt === null) { errors.push(`event ${event.event_index}: committed event is incomplete`); continue; } const raw = raw64(record.seed, BigInt(event.event_index), event.purpose, event.attempt); if (raw.toString() !== event.raw64) errors.push(`event ${event.event_index}: raw64 mismatch`); if (event.interpreted_result?.face !== undefined && Number(raw % 6n) + 1 !== event.interpreted_result.face) errors.push(`event ${event.event_index}: d6 result mismatch`); if (event.interpreted_result?.j !== undefined) { const bound = (event.interpreted_result as { bound?: number }).bound; if (!bound || Number(raw % BigInt(bound)) !== event.interpreted_result.j) errors.push(`event ${event.event_index}: shuffle result mismatch`); } } return { passed: errors.length === 0 && record.reproducibility.status === "reproducible_with_documented_reconciliation", eventCount: record.rng_event_ledger.length, orphanedEventCount: orphaned, errors }; }

type GoldenInput = { seq: number; labor: number; action: string; [key: string]: unknown };
type ReplayScript = GoldenRunRecord & { difficulty: string; inputs: GoldenInput[]; id_map: { rewards: Record<string, string>; }; expected_final_next_event: number; };
const recordValue = (value: unknown): Record<string, unknown> => value as Record<string, unknown>;
const rewards = () => GAME_DATA.labors.flatMap((labor) => (labor.rewards as unknown as Record<string, unknown>[] | undefined) ?? []);
function rewardId(script: ReplayScript, externalId: string): string { if (externalId === "COMPONENT_BOW_OF_HERCULES") return "component.bow"; const name = script.id_map.rewards[externalId]; const found = rewards().find((reward) => reward.name === name); if (!found) throw new Error(`Golden reward mapping is missing ${externalId}.`); return found.id as string; }
function abilityId(script: ReplayScript, externalId: string): string { const [externalReward, suffix] = externalId.split(":"); if (externalReward === "COMPONENT_BOW_OF_HERCULES") return "ability.bow.blue"; const id = rewardId(script, externalReward), reward = recordValue(rewards().find((entry) => entry.id === id)); const color = suffix === "GOLD" ? "gold" : "blue"; const abilities = (reward[color] as Record<string, unknown>[] | undefined) ?? []; const variant = suffix === "A" || suffix === "B" ? suffix : ""; const found = abilities.find((entry) => String(entry.id).endsWith(`${color}${variant}`)); if (!found) throw new Error(`Golden ability mapping is missing ${externalId}.`); return found.id as string; }
function laborDieId(state: GameState, externalId: string): string { const dice = Object.keys(state.currentLabor?.laborDice ?? {}); const match = externalId.match(/_(D1|L|R|A|B|C\d+)$/); if (!match) throw new Error(`Unknown Golden Labor die ${externalId}.`); const token = match[1]; const found = dice.find((id) => token === "D1" ? id.endsWith(".d1") : token === "L" ? id.endsWith(".left") : token === "R" ? id.endsWith(".right") : id.endsWith(`.${token}`)); if (!found) throw new Error(`Golden Labor die ${externalId} is not present in ${state.currentLabor?.laborId}.`); return found; }
function finishBlueForHistoricalPlacement(state: GameState): GameState { if (state.game.phase !== "BLUE_ABILITY_WINDOW") return state; const next = structuredClone(state); next.game.phase = "GOLD_AND_ATTACK_PLACEMENT"; return next; }
function consumeGoldenLaborOneOrphans(state: GameState): GameState { if (state.game.currentLaborId !== "labor.L01" || state.rng.nextEvent !== "18") return state; const next = structuredClone(state); for (let event = 18; event <= 25; event += 1) next.rng.ledger.push({ eventIndex: String(event), purpose: `golden_reconciliation:orphaned_labor1_transition:${event}`, attempt: 0, result: null, status: "orphaned_execution_error", error: "Documented Golden Run 0001 reconciliation: invalid prose-generated transition shuffle." }); next.rng.nextEvent = "26"; return next; }
type TransitionResult = { state: GameState; checkpoint?: GameState };
function resolveAndAdvance(state: GameState): TransitionResult { let next = resolveAssignments(state); if (next.pendingDecision) throw new Error("Golden script reached an undocumented meaningful-placement confirmation."); if (next.game.phase === "DAMAGE_RESOLUTION") next = resolveRoundDamage(next); return finishRewardTransition(next); }
function finishRewardTransition(state: GameState): TransitionResult { if (state.game.phase !== "LABOR_TRANSITION") return { state }; const completed = completeLaborTransitionWithCheckpoint(consumeGoldenLaborOneOrphans(state)); return { state: completed.state, checkpoint: completed.checkpoint }; }
/** Executes the normalized Golden player inputs through public engine operations. */
export function replayGoldenRunTrace(script: ReplayScript): { state: GameState; checkpoints: GameState[] } {
  let state = initializeGame("human", script.seed);
  const snapshots: GameState[] = [];
  const checkpoints: GameState[] = [];
  for (const input of script.inputs) {
    if (input.action === "approve_initial_mood_input_order") continue;
    if (input.action === "roll") { try { state = rollFromRng(state); } catch (error) { throw new Error(`Golden roll input ${input.seq} failed in ${state.game.phase} (pending=${state.pendingDecision?.type ?? "none"}, nodes=${Object.values(state.currentLabor?.laborDice ?? {}).map(die=>die.nodeId).join(",")}): ${error instanceof Error ? error.message : String(error)}`); } continue; }
    if (input.action === "finalize_blue_phase") { snapshots.push(structuredClone(state)); state = structuredClone(state); state.game.phase = "GOLD_AND_ATTACK_PLACEMENT"; continue; }
    if (input.action === "undo_last_deterministic_action") { const snapshot = snapshots.pop(); if (!snapshot) throw new Error(`Golden undo at ${input.seq} has no deterministic checkpoint.`); if (snapshot.rng.nextEvent !== state.rng.nextEvent) throw new Error(`Golden undo at ${input.seq} crosses an RNG boundary.`); state = snapshot; continue; }
    if (input.action === "use_blue") { snapshots.push(structuredClone(state)); const operation = recordValue(input.operation), id = abilityId(script, input.ability_id as string); const target = id === "ability.bow.blue" ? Number(operation.to) - Number(operation.from) : operation.to as number; try { state = useBlueAbility(state, id, input.die_id as string, target); } catch (error) { throw new Error(`Golden blue input ${input.seq} (${input.ability_id as string}) failed: ${error instanceof Error ? error.message : String(error)}`); } continue; }
    if (input.action === "reroll") { state = useRerollOne(state, abilityId(script, input.ability_id as string), input.die_id as string); continue; }
    if (input.action === "use_blue_cows_b_and_reroll") { state = useCowsB(state, input.source_die_id as string, input.reroll_die_ids as string[]); continue; }
    if (input.action === "assign_attack" || input.action === "assign_attack_sets") { state = finishBlueForHistoricalPlacement(state); snapshots.push(structuredClone(state)); const target = laborDieId(state, input.target_id as string); const sets = input.action === "assign_attack_sets" ? input.sets as string[][] : (input.attack_instances as number) > 1 ? (input.dice as string[]).map((die) => [die]) : [input.dice as string[]]; try { for (const set of sets) state = allocateAttack(state, target, set); } catch (error) { throw new Error(`Golden attack input ${input.seq} (${input.target_id as string}) failed: ${error instanceof Error ? error.message : String(error)}`); } continue; }
    if (input.action === "place_gold") { state = finishBlueForHistoricalPlacement(state); snapshots.push(structuredClone(state)); state = placeGoldAbility(state, abilityId(script, input.ability_id as string), input.dice as string[]); continue; }
    if (input.action === "resolve_assignments") { try { const result=resolveAndAdvance(state); state=result.state; if(result.checkpoint)checkpoints.push(result.checkpoint); } catch (error) { throw new Error(`Golden resolve input ${input.seq} failed: ${error instanceof Error ? error.message : String(error)}`); } continue; }
    if (input.action === "choose_broken_die") { if (state.pendingDecision?.type === "CHOOSE_DIE_TO_BREAK") state = chooseBrokenDie(state, state.pendingDecision.id, input.die_id as string); continue; }
    if (input.action === "choose_reward") { state = chooseReward(state, rewardId(script, input.reward_id as string)); const result=finishRewardTransition(state);state=result.state;if(result.checkpoint)checkpoints.push(result.checkpoint);continue; }
    if (input.action === "remove_prior_reward_or_component") { state = chooseRewardToRemove(state, state.pendingDecision?.id ?? "", rewardId(script, input.target_id as string)); const result=finishRewardTransition(state);state=result.state;if(result.checkpoint)checkpoints.push(result.checkpoint);continue; }
    throw new Error(`Unsupported Golden action ${input.action} at ${input.seq}.`);
  }
  if (Number(state.rng.nextEvent) !== script.expected_final_next_event) throw new Error(`Golden replay next event mismatch: expected ${script.expected_final_next_event}, got ${state.rng.nextEvent}.`);
  return { state, checkpoints };
}
export function replayGoldenRun(script: ReplayScript): GameState { return replayGoldenRunTrace(script).state; }
